language: php
php:
  - 5.6
  - 5.5
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: 7.0
install:
  - composer install
  - mkdir -p build/logs
script: phpunit
after_script:
  - php vendor/bin/coveralls
