language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
install:
  - composer install
  - mkdir -p build/logs
script: phpunit
after_script:
  - php vendor/bin/coveralls
